FROM eclipse-temurin:21-jre

WORKDIR /app

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} application.jar
COPY src/main/resources/application.yaml application.yaml

CMD ["java", "-jar", "application.jar", "--spring.config.location=file:/app/application.yaml"]



