server:
  port: 8085

spring:
  application:
    name: countrytest

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

      settings:
        web-allow-others: true

country:
  endpoint: http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso
#
#  kafka:
#    #    bootstrap-servers: kafka:9092
#    bootstrap-servers: kafka:9092