apiVersion: v1
kind: ConfigMap
metadata:
  name: countrytest-config
data:
  application.yaml: |
    server:
      port: 8085

    spring:
      application:
        name: countrytest
    # Use this to test on h2 in the event that you have challenges installing mysql
    # Use this to see h2 console http://localhost:8085/h2-console
    #  datasource:
    #    url: jdbc:h2:mem:testdb
    #    driver-class-name: org.h2.Driver
    #    username: sa
      datasource:
        url: com.mysql.cj.jdbc.Driver
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true

      h2:
        console:
          enabled: true
          settings:
            web-allow-others: true

    country:
      endpoint: http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso
