apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: countrytest-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: countrytest.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: countrytest
                port:
                  number: 8085
